@echo off
echo Deleting database...
del /q quotes.db 2>nul
echo Generating sqlc...
sqlc generate
if %errorlevel% neq 0 exit /b %errorlevel%
echo Building...
go build -o mchugh-com-au.exe ./cmd/server/
if %errorlevel% neq 0 exit /b %errorlevel%
echo Starting server...
mchugh-com-au.exe
