// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Booking struct {
	ID               int64  `json:"id"`
	Name             string `json:"name"`
	Phone            string `json:"phone"`
	Email            string `json:"email"`
	Suburb           string `json:"suburb"`
	ServiceSlug      string `json:"service_slug"`
	Mode             string `json:"mode"`
	Issue            string `json:"issue"`
	PreferredTime    string `json:"preferred_time"`
	Status           string `json:"status"`
	Ip               string `json:"ip"`
	CreatedAt        string `json:"created_at"`
	CustomerID       int64  `json:"customer_id"`
	StartAt          string `json:"start_at"`
	DurationMin      int64  `json:"duration_min"`
	AdminNotes       string `json:"admin_notes"`
	ParentBookingID  int64  `json:"parent_booking_id"`
	UpdatedAt        string `json:"updated_at"`
	Address          string `json:"address"`
	ReminderSentAt   string `json:"reminder_sent_at"`
	AdminAlertSentAt string `json:"admin_alert_sent_at"`
	GcalEventID      string `json:"gcal_event_id"`
	GcalSyncedAt     string `json:"gcal_synced_at"`
}

type Customer struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	PhoneNorm string `json:"phone_norm"`
	Address   string `json:"address"`
	Suburb    string `json:"suburb"`
	Notes     string `json:"notes"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type GoogleCalendar struct {
	ID            int64  `json:"id"`
	AccountEmail  string `json:"account_email"`
	RefreshToken  string `json:"refresh_token"`
	CalendarID    string `json:"calendar_id"`
	CalendarName  string `json:"calendar_name"`
	SkipCalendars string `json:"skip_calendars"`
	ConnectedAt   string `json:"connected_at"`
	LastSyncAt    string `json:"last_sync_at"`
	LastError     string `json:"last_error"`
}

type Invoice struct {
	ID            int64  `json:"id"`
	Number        int64  `json:"number"`
	BookingID     int64  `json:"booking_id"`
	CustomerID    int64  `json:"customer_id"`
	Status        string `json:"status"`
	IssuedAt      string `json:"issued_at"`
	DueAt         string `json:"due_at"`
	PaidAt        string `json:"paid_at"`
	PaymentMethod string `json:"payment_method"`
	PaymentRef    string `json:"payment_ref"`
	PaymentLink   string `json:"payment_link"`
	TotalCents    int64  `json:"total_cents"`
	Notes         string `json:"notes"`
	ViewToken     string `json:"view_token"`
	ReviewAskedAt string `json:"review_asked_at"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type InvoiceItem struct {
	ID          int64   `json:"id"`
	InvoiceID   int64   `json:"invoice_id"`
	Description string  `json:"description"`
	Qty         float64 `json:"qty"`
	UnitCents   int64   `json:"unit_cents"`
	LineCents   int64   `json:"line_cents"`
	SortOrder   int64   `json:"sort_order"`
}

type Quote struct {
	ID          int64   `json:"id"`
	UserID      int64   `json:"user_id"`
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	Mobile      string  `json:"mobile"`
	Address     string  `json:"address"`
	Description string  `json:"description"`
	TotalCost   float64 `json:"total_cost"`
	Features    string  `json:"features"`
	AiEstimate  string  `json:"ai_estimate"`
	VerifyToken string  `json:"verify_token"`
	VerifiedAt  string  `json:"verified_at"`
	Status      string  `json:"status"`
	CreatedAt   string  `json:"created_at"`
}

type QuoteOption struct {
	ID        int64  `json:"id"`
	GroupID   int64  `json:"group_id"`
	Value     string `json:"value"`
	Name      string `json:"name"`
	Cost      int64  `json:"cost"`
	CostLabel string `json:"cost_label"`
	IsDefault int64  `json:"is_default"`
	SortOrder int64  `json:"sort_order"`
}

type QuoteOptionGroup struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Label     string `json:"label"`
	Hint      string `json:"hint"`
	SortOrder int64  `json:"sort_order"`
}

type QuoteSetting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SchedulerRun struct {
	Job   string `json:"job"`
	RanOn string `json:"ran_on"`
}

type User struct {
	ID        int64  `json:"id"`
	GoogleID  string `json:"google_id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	Picture   string `json:"picture"`
	CreatedAt string `json:"created_at"`
}
