// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Booking struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Phone         string `json:"phone"`
	Email         string `json:"email"`
	Suburb        string `json:"suburb"`
	ServiceSlug   string `json:"service_slug"`
	Mode          string `json:"mode"`
	Issue         string `json:"issue"`
	PreferredTime string `json:"preferred_time"`
	Status        string `json:"status"`
	Ip            string `json:"ip"`
	CreatedAt     string `json:"created_at"`
}

type Quote struct {
	ID          int64   `json:"id"`
	UserID      int64   `json:"user_id"`
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	Mobile      string  `json:"mobile"`
	Address     string  `json:"address"`
	Description string  `json:"description"`
	TotalCost   float64 `json:"total_cost"`
	Features    string  `json:"features"`
	AiEstimate  string  `json:"ai_estimate"`
	VerifyToken string  `json:"verify_token"`
	VerifiedAt  string  `json:"verified_at"`
	Status      string  `json:"status"`
	CreatedAt   string  `json:"created_at"`
}

type QuoteOption struct {
	ID        int64  `json:"id"`
	GroupID   int64  `json:"group_id"`
	Value     string `json:"value"`
	Name      string `json:"name"`
	Cost      int64  `json:"cost"`
	CostLabel string `json:"cost_label"`
	IsDefault int64  `json:"is_default"`
	SortOrder int64  `json:"sort_order"`
}

type QuoteOptionGroup struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Label     string `json:"label"`
	Hint      string `json:"hint"`
	SortOrder int64  `json:"sort_order"`
}

type QuoteSetting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type User struct {
	ID        int64  `json:"id"`
	GoogleID  string `json:"google_id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	Picture   string `json:"picture"`
	CreatedAt string `json:"created_at"`
}
