// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const countOptionGroups = `-- name: CountOptionGroups :one
SELECT COUNT(*) FROM quote_option_groups
`

func (q *Queries) CountOptionGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOptionGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSettingByKey = `-- name: CountSettingByKey :one
SELECT COUNT(*) FROM quote_settings WHERE key = ?
`

func (q *Queries) CountSettingByKey(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSettingByKey, key)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllOptionGroups = `-- name: DeleteAllOptionGroups :exec
DELETE FROM quote_option_groups
`

func (q *Queries) DeleteAllOptionGroups(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllOptionGroups)
	return err
}

const deleteAllOptions = `-- name: DeleteAllOptions :exec
DELETE FROM quote_options
`

func (q *Queries) DeleteAllOptions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllOptions)
	return err
}

const getLastBooking = `-- name: GetLastBooking :one
SELECT id, name, phone, email, suburb, service_slug, mode, issue, preferred_time, status, ip, created_at
FROM bookings WHERE id = (SELECT MAX(id) FROM bookings)
`

func (q *Queries) GetLastBooking(ctx context.Context) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getLastBooking)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Suburb,
		&i.ServiceSlug,
		&i.Mode,
		&i.Issue,
		&i.PreferredTime,
		&i.Status,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const getLastOptionGroup = `-- name: GetLastOptionGroup :one
SELECT id, name, label, hint, sort_order
FROM quote_option_groups WHERE id = (SELECT MAX(id) FROM quote_option_groups)
`

func (q *Queries) GetLastOptionGroup(ctx context.Context) (QuoteOptionGroup, error) {
	row := q.db.QueryRowContext(ctx, getLastOptionGroup)
	var i QuoteOptionGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Hint,
		&i.SortOrder,
	)
	return i, err
}

const getLastQuote = `-- name: GetLastQuote :one
SELECT id, user_id, name, email, mobile, address, description, total_cost, features, ai_estimate, stripe_session_id, status, created_at
FROM quotes WHERE id = (SELECT MAX(id) FROM quotes)
`

func (q *Queries) GetLastQuote(ctx context.Context) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getLastQuote)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Address,
		&i.Description,
		&i.TotalCost,
		&i.Features,
		&i.AiEstimate,
		&i.StripeSessionID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getQuote = `-- name: GetQuote :one
SELECT id, user_id, name, email, mobile, address, description, total_cost, features, ai_estimate, stripe_session_id, status, created_at
FROM quotes WHERE id = ?
`

func (q *Queries) GetQuote(ctx context.Context, id int64) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Address,
		&i.Description,
		&i.TotalCost,
		&i.Features,
		&i.AiEstimate,
		&i.StripeSessionID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one

SELECT value FROM quote_settings WHERE key = ?
`

// Settings
func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, email, name, picture, created_at
FROM users WHERE google_id = ?
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}

const insertBooking = `-- name: InsertBooking :exec

INSERT INTO bookings (name, phone, email, suburb, service_slug, mode, issue, preferred_time, ip)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBookingParams struct {
	Name          string `json:"name"`
	Phone         string `json:"phone"`
	Email         string `json:"email"`
	Suburb        string `json:"suburb"`
	ServiceSlug   string `json:"service_slug"`
	Mode          string `json:"mode"`
	Issue         string `json:"issue"`
	PreferredTime string `json:"preferred_time"`
	Ip            string `json:"ip"`
}

// Bookings
func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) error {
	_, err := q.db.ExecContext(ctx, insertBooking,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Suburb,
		arg.ServiceSlug,
		arg.Mode,
		arg.Issue,
		arg.PreferredTime,
		arg.Ip,
	)
	return err
}

const insertOption = `-- name: InsertOption :exec
INSERT INTO quote_options (group_id, value, name, cost, cost_label, is_default, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertOptionParams struct {
	GroupID   int64  `json:"group_id"`
	Value     string `json:"value"`
	Name      string `json:"name"`
	Cost      int64  `json:"cost"`
	CostLabel string `json:"cost_label"`
	IsDefault int64  `json:"is_default"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) InsertOption(ctx context.Context, arg InsertOptionParams) error {
	_, err := q.db.ExecContext(ctx, insertOption,
		arg.GroupID,
		arg.Value,
		arg.Name,
		arg.Cost,
		arg.CostLabel,
		arg.IsDefault,
		arg.SortOrder,
	)
	return err
}

const insertOptionGroup = `-- name: InsertOptionGroup :exec
INSERT INTO quote_option_groups (name, label, hint, sort_order) VALUES (?, ?, ?, ?)
`

type InsertOptionGroupParams struct {
	Name      string `json:"name"`
	Label     string `json:"label"`
	Hint      string `json:"hint"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) InsertOptionGroup(ctx context.Context, arg InsertOptionGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertOptionGroup,
		arg.Name,
		arg.Label,
		arg.Hint,
		arg.SortOrder,
	)
	return err
}

const insertQuote = `-- name: InsertQuote :exec

INSERT INTO quotes (user_id, name, email, mobile, address, description, total_cost, features, ai_estimate, stripe_session_id, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertQuoteParams struct {
	UserID          int64   `json:"user_id"`
	Name            string  `json:"name"`
	Email           string  `json:"email"`
	Mobile          string  `json:"mobile"`
	Address         string  `json:"address"`
	Description     string  `json:"description"`
	TotalCost       float64 `json:"total_cost"`
	Features        string  `json:"features"`
	AiEstimate      string  `json:"ai_estimate"`
	StripeSessionID string  `json:"stripe_session_id"`
	Status          string  `json:"status"`
}

// Quotes
func (q *Queries) InsertQuote(ctx context.Context, arg InsertQuoteParams) error {
	_, err := q.db.ExecContext(ctx, insertQuote,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.Mobile,
		arg.Address,
		arg.Description,
		arg.TotalCost,
		arg.Features,
		arg.AiEstimate,
		arg.StripeSessionID,
		arg.Status,
	)
	return err
}

const listBookings = `-- name: ListBookings :many
SELECT id, name, phone, email, suburb, service_slug, mode, issue, preferred_time, status, ip, created_at
FROM bookings ORDER BY id DESC
`

func (q *Queries) ListBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Suburb,
			&i.ServiceSlug,
			&i.Mode,
			&i.Issue,
			&i.PreferredTime,
			&i.Status,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftsByUser = `-- name: ListDraftsByUser :many
SELECT id, user_id, name, email, description, total_cost, status, created_at
FROM quotes WHERE user_id = ? AND status = 'draft'
ORDER BY created_at DESC
`

type ListDraftsByUserRow struct {
	ID          int64   `json:"id"`
	UserID      int64   `json:"user_id"`
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	Description string  `json:"description"`
	TotalCost   float64 `json:"total_cost"`
	Status      string  `json:"status"`
	CreatedAt   string  `json:"created_at"`
}

func (q *Queries) ListDraftsByUser(ctx context.Context, userID int64) ([]ListDraftsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDraftsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftsByUserRow
	for rows.Next() {
		var i ListDraftsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Description,
			&i.TotalCost,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionGroups = `-- name: ListOptionGroups :many

SELECT id, name, label, hint, sort_order
FROM quote_option_groups ORDER BY sort_order, id
`

// Option Groups
func (q *Queries) ListOptionGroups(ctx context.Context) ([]QuoteOptionGroup, error) {
	rows, err := q.db.QueryContext(ctx, listOptionGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuoteOptionGroup
	for rows.Next() {
		var i QuoteOptionGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Label,
			&i.Hint,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByGroupID = `-- name: ListOptionsByGroupID :many
SELECT id, group_id, value, name, cost, cost_label, is_default, sort_order
FROM quote_options WHERE group_id = ? ORDER BY sort_order, id
`

func (q *Queries) ListOptionsByGroupID(ctx context.Context, groupID int64) ([]QuoteOption, error) {
	rows, err := q.db.QueryContext(ctx, listOptionsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuoteOption
	for rows.Next() {
		var i QuoteOption
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Value,
			&i.Name,
			&i.Cost,
			&i.CostLabel,
			&i.IsDefault,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaidByUser = `-- name: ListPaidByUser :many
SELECT id, user_id, name, email, mobile, address, description, total_cost, features, ai_estimate, stripe_session_id, status, created_at
FROM quotes WHERE user_id = ? AND status = 'paid'
ORDER BY created_at DESC
`

func (q *Queries) ListPaidByUser(ctx context.Context, userID int64) ([]Quote, error) {
	rows, err := q.db.QueryContext(ctx, listPaidByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quote
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Mobile,
			&i.Address,
			&i.Description,
			&i.TotalCost,
			&i.Features,
			&i.AiEstimate,
			&i.StripeSessionID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotes = `-- name: ListQuotes :many
SELECT id, user_id, name, email, mobile, address, description, total_cost, features, ai_estimate, stripe_session_id, status, created_at
FROM quotes ORDER BY created_at DESC
`

func (q *Queries) ListQuotes(ctx context.Context) ([]Quote, error) {
	rows, err := q.db.QueryContext(ctx, listQuotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quote
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Mobile,
			&i.Address,
			&i.Description,
			&i.TotalCost,
			&i.Features,
			&i.AiEstimate,
			&i.StripeSessionID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :exec
UPDATE bookings SET status = ? WHERE id = ?
`

type UpdateBookingStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBookingStatus, arg.Status, arg.ID)
	return err
}

const updateQuoteStatus = `-- name: UpdateQuoteStatus :exec
UPDATE quotes SET status = ?, stripe_session_id = ?, ai_estimate = ?
WHERE id = ?
`

type UpdateQuoteStatusParams struct {
	Status          string `json:"status"`
	StripeSessionID string `json:"stripe_session_id"`
	AiEstimate      string `json:"ai_estimate"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateQuoteStatus(ctx context.Context, arg UpdateQuoteStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateQuoteStatus,
		arg.Status,
		arg.StripeSessionID,
		arg.AiEstimate,
		arg.ID,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT OR REPLACE INTO quote_settings (key, value) VALUES (?, ?)
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}

const upsertUser = `-- name: UpsertUser :exec

INSERT INTO users (google_id, email, name, picture)
VALUES (?, ?, ?, ?)
ON CONFLICT(google_id) DO UPDATE SET
    email = excluded.email,
    name = excluded.name,
    picture = excluded.picture
`

type UpsertUserParams struct {
	GoogleID string `json:"google_id"`
	Email    string `json:"email"`
	Name     string `json:"name"`
	Picture  string `json:"picture"`
}

// Users
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.Picture,
	)
	return err
}
